### ISSUE TITLE
Releases cannot be deserialized

### ISSUE THREAD

**Issue by MitchTalmadge** [heroku/heroku.jar#78]
When trying to list releases, I get this exception:

```java
org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@377c4e56; line: 1, column: 716] (through reference chain: com.heroku.api.Release["pstable"])
	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:219) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.std.StringDeserializer.deserialize(StringDeserializer.java:44) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.std.StringDeserializer.deserialize(StringDeserializer.java:13) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:319) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:194) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1973) ~[jackson-mapper-asl-1.9.10.jar:1.9.10]
	at com.heroku.api.parser.JacksonParser.parse(JacksonParser.java:23) ~[heroku-json-jackson-0.16.jar:na]
	at com.heroku.api.parser.Json.parse(Json.java:70) ~[heroku-api-0.16.jar:na]
	at com.heroku.api.request.releases.ListReleases.getResponse(ListReleases.java:63) ~[heroku-api-0.16.jar:na]
	at com.heroku.api.request.releases.ListReleases.getResponse(ListReleases.java:22) ~[heroku-api-0.16.jar:na]
	at com.heroku.api.connection.HttpClientConnection.execute(HttpClientConnection.java:101) ~[heroku-http-apache-0.16.jar:na]
	at com.heroku.api.connection.HttpClientConnection.execute(HttpClientConnection.java:67) ~[heroku-http-apache-0.16.jar:na]
	at com.heroku.api.HerokuAPI.listReleases(HerokuAPI.java:296) ~[heroku-api-0.16.jar:na]
```

I have narrowed it down to this section of `Release.java`: 
```java
Map<String, String> pstable;
```

Here is an example of what is being sent by Heroku, which will not correctly map to this variable:
```json
"pstable":{  
         "web":{  
            "command":"java -jar target/myapp.jar",
            "slug":{  
               "id":"1234567-a12b-3cd4-5ef6-78901b34a678"
            }
         }
      },
```

Interestingly, this is not at all documented in the [Platform API Reference](https://devcenter.heroku.com/articles/platform-api-reference#release)

**Comment by MitchTalmadge** [comment]
I am using version 0.16. I see now that this appears to be outdated, however the latest version isn't on maven

**Comment by jkutner** [comment]
[0.17](http://repo1.maven.org/maven2/com/heroku/api/heroku-api/0.17/) is in Maven Central now. can you give it a try?

**Comment by jkutner** [comment]
Closing for now. If you still run into this with 0.17 or 0.18 we can reopen.
